Repository retaildevcrews/caf-terraform-landingzones-starter, pull requests merged in 2021-04, with the labels that each got.

#7 NGSA Helm Chart Updated for aks-secure-baseline
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/ngsa/.helmignore
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/ngsa/Chart.yaml
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/ngsa/README.md
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/ngsa/helm-config-ngsa-memory.yaml
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/ngsa/templates/_helpers.tpl
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/ngsa/templates/deployment.yaml
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/ngsa/templates/service.yaml
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/ngsa/templates/serviceaccount.yaml
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/ngsa/values.yaml
Labels: GitOps

#12 Updated terraform scripts to add firewall application rules to allow github container registry
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/configuration/networking/firewall_application_rule_collection_definition.tfvars
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/loderunner/README.md
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/ngsa/README.md
Labels: Terraform

#14 Added clarity to deployment steps & link application deploymnet docs
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/01-terraform.md
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/02-aks.md
Labels: Documentation

#16 Added documentation on AzureIdentityBinding
  enterprise_scale/construction_sets/aks/online/aks_secure_baseline/02-aks.md
Labels: Documentation

#18 Removed terraform.tfvars and improved terraform provisioning script to work on subsequent runs
  enterprise_scale/construction_sets/aks/provision_environment/README.md
  enterprise_scale/construction_sets/aks/provision_environment/_prepare-terraform.sh
  enterprise_scale/construction_sets/aks/provision_environment/provision-environment.sh
  enterprise_scale/construction_sets/aks/variables.tf
Labels: Bug, Terraform
